<a href="https://colab.research.google.com/github/nursedakarabacak/beginnerpython/blob/main/buildingmlpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
import numpy as np

In [78]:
d1 = {'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2200000, 1000000],
'Sold_out':[1,0,0,1,0,0,0,1,0,1]}

In [79]:
df1 = pd.DataFrame(data=d1)

In [80]:
df1

   Social_media_followers  Sold_out
0               1000000.0         1
1                     NaN         0
2               2000000.0         0
3               1310000.0         1
4               1700000.0         0
5                     NaN         0
6               4100000.0         0
7               1600000.0         1
8               2200000.0         0
9               1000000.0         1

In [82]:
X1 = df1[['Social_media_followers']] #2 boyutlu olması için

In [81]:
y1 = [['Sold_out']]

In [83]:
#split our data also a few nwe cells  train test
from sklearn.model_selection import train_test_split

In [60]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, df1['Sold_out'], test_size=0.3,random_state=19)

In [84]:
X1_train.shape

(7, 1)

In [63]:
X1_test.shape

(3, 1)

In [85]:
from sklearn.impute import SimpleImputer

In [86]:
imputer = SimpleImputer(strategy ='mean')

In [87]:
from sklearn.linear_model import LogisticRegression

In [88]:
lr = LogisticRegression()

In [89]:
from sklearn.pipeline import make_pipeline

In [90]:
pipe1 = make_pipeline(imputer, lr)

In [91]:
pipe1.fit(X1_train, y1_train)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('logisticregression', LogisticRegression())])

In [92]:
pipe1.score(X1_test, y1_test)

0.6666666666666666

In [74]:
pipe1.named_steps.simpleimputer.statistics_

array([2051666.66666667])

In [93]:
#more advenced pipeline
d2 = {'Genre':['Rock', 'Metal', 'Bluegrass', 'Rock', np.nan, 'Rock', 'Rock', np.nan, 'Bluegrass', 'Rock'],
    'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2200000, 1000000],
    'Sold_out':[1,0,0,1,0,0,0,1,0,1]}

In [102]:
df2 = pd.DataFrame(data=d2)

In [104]:
df2

       Genre  Social_media_followers  Sold_out
0       Rock               1000000.0         1
1      Metal                     NaN         0
2  Bluegrass               2000000.0         0
3       Rock               1310000.0         1
4        NaN               1700000.0         0
5       Rock                     NaN         0
6       Rock               4100000.0         0
7        NaN               1600000.0         1
8  Bluegrass               2200000.0         0
9       Rock               1000000.0         1

In [147]:
X = df2.iloc[:,0:2]

In [148]:
y= df2.iloc[:,2]

In [149]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=19)

In [150]:
#cotegorizing our numeric and  categorical columns
num_cols = ['Social_media_followers']
cat=['Genre']

In [151]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [152]:
num_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='mean')),
    ('scale',StandardScaler())
])

In [153]:
cat_pipeline = Pipeline(steps=[
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('one-hot',OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [154]:
from sklearn.compose import ColumnTransformer

In [155]:
col_trans = ColumnTransformer(transformers=[
('num_pipeline',num_pipeline,num_cols),
('cat_pipeline',cat_pipeline,cat)
],
remainder='drop',
n_jobs=-1)

In [156]:
from sklearn.tree import DecisionTreeClassifier

In [157]:
dtc = DecisionTreeClassifier()

In [158]:
pipefinal = make_pipeline(col_trans, dtc)

In [159]:
pipefinal.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['Social_media_followers']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Genre'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])